module.exports = {
    ZipCode: 'address.zipCode',
    City: 'address.city',
    CityPrefix: 'address.cityPrefix',
    CitySuffix: 'address.citySuffix',
    StreetName: 'address.streetName',
    StreetAddress: 'address.streetAddress',
    StreetSuffix: 'address.streetSuffix',
    StreetPrefix: 'address.streetPrefix',
    SecondaryAddress: 'address.secondaryAddress',
    County: 'address.county',
    Country: 'address.country',
    CountryCode: 'address.countryCode',
    State: 'address.state',
    StateAbbr: 'address.stateAbbr',
    Latitude: 'address.latitude',
    Longitude: 'address.longitude',

    Color: 'commerce.color',
    Department: 'commerce.department',
    ProductName: 'commerce.productName',
    Price: 'commerce.price',
    ProductAdjective: 'commerce.productAdjective',
    ProductMaterial: 'commerce.productMaterial',
    Product: 'commerce.product',

    CompanyName: 'company.companyName',
    CompanySuffix: 'company.companySuffix',
    CatchPhrase: 'company.catchPhrase',
    Bs: 'company.bs',
    CatchPhraseAdjective: 'company.catchPhraseAdjective',
    CatchPhraseDescriptor: 'company.catchPhraseDescriptor',
    CatchPhraseNoun: 'company.catchPhraseNoun',
    BsAdjective: 'company.bsAdjective',
    BsBuzz: 'company.bsBuzz',
    BsNoun: 'company.bsNoun',

    DatabaseColumn: 'database.column',
    DatabaseType: 'database.type',
    DatabaseCollation: 'database.collation',
    DatabaseEngine: 'database.engine',

    DatePast: 'date.past',
    DateFuture: 'date.future',
    DateBetween: 'date.between',
    DateRecent: 'date.recent',
    Month: 'date.month',
    Weekday: 'date.weekday',

    BankAccount: 'finance.account',
    BankAccountName: 'finance.accountName',
    CreditCardMask: 'finance.mask',
    CurrencyAmount: 'finance.amount',
    TransactionType: 'finance.transactionType',
    CurrencyCode: 'finance.currencyCode',
    CurrencyName: 'finance.currencyName',
    CurrencySymbol: 'finance.currencySymbol',
    Bitcoin: 'finance.bitcoinAddress',
    BankAccountIban: 'finance.iban',
    BankAccountBic: 'finance.bic',

    Abbreviation: 'hacker.abbreviation',
    Adjective: 'hacker.adjective',
    Noun: 'hacker.noun',
    Verb: 'hacker.verb',
    Ingverb: 'hacker.ingverb',
    Phrase: 'hacker.phrase',

    Image: 'image.image',
    AvatarImage: 'image.avatar',
    ImageUrl: 'image.imageUrl',
    AbstractImage: 'image.abstract',
    AnimalsImage: 'image.animals',
    BusinessImage: 'image.business',
    CatsImage: 'image.cats',
    CityImage: 'image.city',
    FoodImage: 'image.food',
    NightlifeImage: 'image.nightlife',
    FashionImage: 'image.fashion',
    PeopleImage: 'image.people',
    NatureImage: 'image.nature',
    SportsImage: 'image.sports',
    TechnicsImage: 'image.technics',
    TransportImage: 'image.transport',
    ImageDataUri: 'image.dataUri',

    Email: 'internet.email',
    ExampleEmail: 'internet.exampleEmail',
    UserName: 'internet.userName',
    Protocol: 'internet.protocol',
    Url: 'internet.url',
    DomainName: 'internet.domainName',
    DomainSuffix: 'internet.domainSuffix',
    DomainWord: 'internet.domainWord',
    IP: 'internet.ip',
    IPV6: 'internet.ipv6',
    UserAgent: 'internet.userAgent',
    HexColor: 'internet.color',
    MACAddress: 'internet.mac',
    Password: 'internet.password',

    LoremWord: 'lorem.word',
    LoremWords: 'lorem.words',
    LoremSentence: 'lorem.sentence',
    LoremSlug: 'lorem.slug',
    LoremSentences: 'lorem.sentences',
    LoremParagraph: 'lorem.paragraph',
    LoremParagraphs: 'lorem.paragraphs',
    LoremText: 'lorem.text',
    LoremLines: 'lorem.lines',

    FirstName: 'name.firstName',
    LastName: 'name.lastName',
    FullName: 'name.findName',
    JobTitle: 'name.jobTitle',
    NamePrefix: 'name.prefix',
    NameSuffix: 'name.suffix',
    NameTitle: 'name.title',
    JobDescriptor: 'name.jobDescriptor',
    JobArea: 'name.jobArea',
    JobType: 'name.jobType',

    PhoneNumber: 'phone.phoneNumber',
    PhoneNumberFormat: 'phone.phoneNumberFormat',
    PhoneFormats: 'phone.phoneFormats',

    ArrayElement: 'random.arrayElement',
    ObjectElement: 'random.objectElement',
    UUID: 'random.uuid',
    Boolean: 'random.boolean',
    Word: 'random.word',
    Words: 'random.words',
    Locale: 'random.locale',
    AlphaNumeric: 'random.alphaNumeric',

    FileName: 'system.fileName',
    CommonFileName: 'system.commonFileName',
    MimeType: 'system.mimeType',
    CommonFileType: 'system.commonFileType',
    CommonFileExt: 'system.commonFileExt',
    FileType: 'system.fileType',
    FileExt: 'system.fileExt',
    DirectoryPath: 'system.directoryPath',
    FilePath: 'system.filePath',
    Semver: 'system.semver'
};
